# Set update schedule for GitHub Actions, Go modules, and container images

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    # Check for updates to Go modules every week
    interval: "weekly"
  groups:
    go-dependencies:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    # Check for updates to container base images every week
    interval: "weekly"
  groups:
    container-images:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"
