apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: storage-secrets-reader
  namespace: osac-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
