//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/role_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Synchronization states for Role resources with the underlying authorization system.
type RoleState int32

const (
	// State is unknown or has not been determined yet.
	RoleState_ROLE_STATE_UNSPECIFIED RoleState = 0
	// The role is being created or applied to the underlying authorization system and cannot be used yet.
	RoleState_ROLE_STATE_PENDING RoleState = 1
	// The role is fully synchronized with the underlying authorization system and can be used.
	RoleState_ROLE_STATE_READY RoleState = 2
	// The role failed to be applied to the underlying authorization system.
	RoleState_ROLE_STATE_FAILED RoleState = 3
)

// Enum value maps for RoleState.
var (
	RoleState_name = map[int32]string{
		0: "ROLE_STATE_UNSPECIFIED",
		1: "ROLE_STATE_PENDING",
		2: "ROLE_STATE_READY",
		3: "ROLE_STATE_FAILED",
	}
	RoleState_value = map[string]int32{
		"ROLE_STATE_UNSPECIFIED": 0,
		"ROLE_STATE_PENDING":     1,
		"ROLE_STATE_READY":       2,
		"ROLE_STATE_FAILED":      3,
	}
)

func (x RoleState) Enum() *RoleState {
	p := new(RoleState)
	*p = x
	return p
}

func (x RoleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_role_type_proto_enumTypes[0].Descriptor()
}

func (RoleState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_role_type_proto_enumTypes[0]
}

func (x RoleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a role that can be assigned to groups.
//
// Roles are predefined named entities that represent a set of permissions within the system. They are assigned to
// groups to control what actions the members of those groups can perform. Roles themselves do not carry any data
// beyond their identity and metadata; the actual permissions are determined by the system based on the role name.
//
// Examples of predefined roles include `cloud-provider-admin`, `tenant-admin`, and `tenant-reader`.
type Role struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the role.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the role.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state of the role.
	Spec *RoleSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current observed state of the role.
	Status        *RoleStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_osac_private_v1_role_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Role) GetSpec() *RoleSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Role) GetStatus() *RoleStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Role) SetId(v string) {
	x.Id = v
}

func (x *Role) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *Role) SetSpec(v *RoleSpec) {
	x.Spec = v
}

func (x *Role) SetStatus(v *RoleStatus) {
	x.Status = v
}

func (x *Role) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Role) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *Role) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *Role) ClearMetadata() {
	x.Metadata = nil
}

func (x *Role) ClearSpec() {
	x.Spec = nil
}

func (x *Role) ClearStatus() {
	x.Status = nil
}

type Role_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the role.
	Id string
	// Metadata of the role.
	Metadata *Metadata
	// Desired state of the role.
	Spec *RoleSpec
	// Current observed state of the role.
	Status *RoleStatus
}

func (b0 Role_builder) Build() *Role {
	m0 := &Role{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Desired state of a role.
type RoleSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Human-friendly short description of the role, only a few words, suitable for displaying in one single line on
	// a UI or CLI. For example: "Cloud Provider Administrator" or "Tenant Reader".
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Human-friendly long description of the role, using Markdown format. This should explain what permissions the
	// role grants and in what contexts it is typically used.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSpec) Reset() {
	*x = RoleSpec{}
	mi := &file_osac_private_v1_role_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSpec) ProtoMessage() {}

func (x *RoleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoleSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleSpec) SetTitle(v string) {
	x.Title = v
}

func (x *RoleSpec) SetDescription(v string) {
	x.Description = v
}

type RoleSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Human-friendly short description of the role, only a few words, suitable for displaying in one single line on
	// a UI or CLI. For example: "Cloud Provider Administrator" or "Tenant Reader".
	Title string
	// Human-friendly long description of the role, using Markdown format. This should explain what permissions the
	// role grants and in what contexts it is typically used.
	Description string
}

func (b0 RoleSpec_builder) Build() *RoleSpec {
	m0 := &RoleSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Title = b.Title
	x.Description = b.Description
	return m0
}

// Current observed state of a role, reflecting its synchronization with the underlying authorization system.
type RoleStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current synchronization state of the role.
	State RoleState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.RoleState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this field may explain why the synchronization with the authorization system failed.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleStatus) Reset() {
	*x = RoleStatus{}
	mi := &file_osac_private_v1_role_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleStatus) ProtoMessage() {}

func (x *RoleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleStatus) GetState() RoleState {
	if x != nil {
		return x.State
	}
	return RoleState_ROLE_STATE_UNSPECIFIED
}

func (x *RoleStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *RoleStatus) SetState(v RoleState) {
	x.State = v
}

func (x *RoleStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *RoleStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *RoleStatus) ClearMessage() {
	x.Message = nil
}

type RoleStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current synchronization state of the role.
	State RoleState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this field may explain why the synchronization with the authorization system failed.
	Message *string
}

func (b0 RoleStatus_builder) Build() *RoleStatus {
	m0 := &RoleStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	return m0
}

var File_osac_private_v1_role_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_role_type_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a, 0x08, 0x52,
	0x6f, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x69, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x6c, 0x0a, 0x09, 0x52, 0x6f,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x4f, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10,
	0x02, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xd2, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x42, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73,
	0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61,
	0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63,
	0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_role_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_role_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_role_type_proto_goTypes = []any{
	(RoleState)(0),     // 0: osac.private.v1.RoleState
	(*Role)(nil),       // 1: osac.private.v1.Role
	(*RoleSpec)(nil),   // 2: osac.private.v1.RoleSpec
	(*RoleStatus)(nil), // 3: osac.private.v1.RoleStatus
	(*Metadata)(nil),   // 4: osac.private.v1.Metadata
}
var file_osac_private_v1_role_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.Role.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.Role.spec:type_name -> osac.private.v1.RoleSpec
	3, // 2: osac.private.v1.Role.status:type_name -> osac.private.v1.RoleStatus
	0, // 3: osac.private.v1.RoleStatus.state:type_name -> osac.private.v1.RoleState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_role_type_proto_init() }
func file_osac_private_v1_role_type_proto_init() {
	if File_osac_private_v1_role_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_role_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_role_type_proto_rawDesc), len(file_osac_private_v1_role_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_role_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_role_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_role_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_role_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_role_type_proto = out.File
	file_osac_private_v1_role_type_proto_goTypes = nil
	file_osac_private_v1_role_type_proto_depIdxs = nil
}
