//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/role_binding_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Synchronization states for RoleBinding objects with the underlying authorization system.
type RoleBindingState int32

const (
	// State is unknown or has not been determined yet.
	RoleBindingState_ROLE_BINDING_STATE_UNSPECIFIED RoleBindingState = 0
	// The role binding is being applied to the underlying authorization system and is not yet effective.
	RoleBindingState_ROLE_BINDING_STATE_PENDING RoleBindingState = 1
	// The role binding is fully synchronized with the underlying authorization system and is effective.
	RoleBindingState_ROLE_BINDING_STATE_READY RoleBindingState = 2
	// The role binding failed to be applied to the underlying authorization system.
	RoleBindingState_ROLE_BINDING_STATE_FAILED RoleBindingState = 3
)

// Enum value maps for RoleBindingState.
var (
	RoleBindingState_name = map[int32]string{
		0: "ROLE_BINDING_STATE_UNSPECIFIED",
		1: "ROLE_BINDING_STATE_PENDING",
		2: "ROLE_BINDING_STATE_READY",
		3: "ROLE_BINDING_STATE_FAILED",
	}
	RoleBindingState_value = map[string]int32{
		"ROLE_BINDING_STATE_UNSPECIFIED": 0,
		"ROLE_BINDING_STATE_PENDING":     1,
		"ROLE_BINDING_STATE_READY":       2,
		"ROLE_BINDING_STATE_FAILED":      3,
	}
)

func (x RoleBindingState) Enum() *RoleBindingState {
	p := new(RoleBindingState)
	*p = x
	return p
}

func (x RoleBindingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleBindingState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_role_binding_type_proto_enumTypes[0].Descriptor()
}

func (RoleBindingState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_role_binding_type_proto_enumTypes[0]
}

func (x RoleBindingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a binding between a role and a set of subjects (groups).
//
// A RoleBinding grants the permissions defined by its referenced role to the subjects listed in its spec. This is
// the mechanism by which roles are assigned to groups, enabling the members of those groups to perform the actions
// permitted by the role.
//
// The subjects of a RoleBinding are groups as defined by the identity provider (IDP) of the tenant. This service
// does not manage groups directly; it references them by their IDP-assigned identifiers. For example, if a tenant
// uses Keycloak as its identity provider, the values in the `groups` field correspond to the names of Keycloak
// groups within the tenant's realm.
type RoleBinding struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the role binding.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the role binding.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state of the role binding.
	Spec *RoleBindingSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current observed state of the role binding.
	Status        *RoleBindingStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	mi := &file_osac_private_v1_role_binding_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_binding_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBinding) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoleBinding) GetSpec() *RoleBindingSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RoleBinding) GetStatus() *RoleBindingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RoleBinding) SetId(v string) {
	x.Id = v
}

func (x *RoleBinding) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *RoleBinding) SetSpec(v *RoleBindingSpec) {
	x.Spec = v
}

func (x *RoleBinding) SetStatus(v *RoleBindingStatus) {
	x.Status = v
}

func (x *RoleBinding) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *RoleBinding) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *RoleBinding) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *RoleBinding) ClearMetadata() {
	x.Metadata = nil
}

func (x *RoleBinding) ClearSpec() {
	x.Spec = nil
}

func (x *RoleBinding) ClearStatus() {
	x.Status = nil
}

type RoleBinding_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the role binding.
	Id string
	// Metadata of the role binding.
	Metadata *Metadata
	// Desired state of the role binding.
	Spec *RoleBindingSpec
	// Current observed state of the role binding.
	Status *RoleBindingStatus
}

func (b0 RoleBinding_builder) Build() *RoleBinding {
	m0 := &RoleBinding{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Desired state of a role binding.
type RoleBindingSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Identifier of the role that this binding refers to. This determines which permissions are granted to the
	// subjects listed below.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Identifiers of the groups that are granted the permissions defined by the role. These are group identifiers
	// as defined by the identity provider (IDP) of the tenant, not internal system identifiers. For example, in a
	// Keycloak-based deployment these would be the Keycloak group names within the tenant's realm.
	Groups        []string `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingSpec) Reset() {
	*x = RoleBindingSpec{}
	mi := &file_osac_private_v1_role_binding_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingSpec) ProtoMessage() {}

func (x *RoleBindingSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_binding_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoleBindingSpec) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *RoleBindingSpec) SetRole(v string) {
	x.Role = v
}

func (x *RoleBindingSpec) SetGroups(v []string) {
	x.Groups = v
}

type RoleBindingSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Identifier of the role that this binding refers to. This determines which permissions are granted to the
	// subjects listed below.
	Role string
	// Identifiers of the groups that are granted the permissions defined by the role. These are group identifiers
	// as defined by the identity provider (IDP) of the tenant, not internal system identifiers. For example, in a
	// Keycloak-based deployment these would be the Keycloak group names within the tenant's realm.
	Groups []string
}

func (b0 RoleBindingSpec_builder) Build() *RoleBindingSpec {
	m0 := &RoleBindingSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Role = b.Role
	x.Groups = b.Groups
	return m0
}

// Current observed state of a role binding, reflecting its synchronization with the underlying authorization system.
type RoleBindingStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current synchronization state of the role binding.
	State RoleBindingState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.RoleBindingState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this field may explain why the synchronization with the authorization system failed.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingStatus) Reset() {
	*x = RoleBindingStatus{}
	mi := &file_osac_private_v1_role_binding_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingStatus) ProtoMessage() {}

func (x *RoleBindingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_binding_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingStatus) GetState() RoleBindingState {
	if x != nil {
		return x.State
	}
	return RoleBindingState_ROLE_BINDING_STATE_UNSPECIFIED
}

func (x *RoleBindingStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *RoleBindingStatus) SetState(v RoleBindingState) {
	x.State = v
}

func (x *RoleBindingStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *RoleBindingStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *RoleBindingStatus) ClearMessage() {
	x.Message = nil
}

type RoleBindingStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current synchronization state of the role binding.
	State RoleBindingState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this field may explain why the synchronization with the authorization system failed.
	Message *string
}

func (b0 RoleBindingStatus_builder) Build() *RoleBindingStatus {
	m0 := &RoleBindingStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	return m0
}

var File_osac_private_v1_role_binding_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_role_binding_type_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc6, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3a, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65,
	0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x77, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2a, 0x93, 0x01, 0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x42, 0x49,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x4f, 0x4c,
	0x45, 0x5f, 0x42, 0x49, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x52, 0x4f, 0x4c,
	0x45, 0x5f, 0x42, 0x49, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x42, 0x49, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xd9, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x14,
	0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61,
	0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f,
	0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_role_binding_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_role_binding_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_role_binding_type_proto_goTypes = []any{
	(RoleBindingState)(0),     // 0: osac.private.v1.RoleBindingState
	(*RoleBinding)(nil),       // 1: osac.private.v1.RoleBinding
	(*RoleBindingSpec)(nil),   // 2: osac.private.v1.RoleBindingSpec
	(*RoleBindingStatus)(nil), // 3: osac.private.v1.RoleBindingStatus
	(*Metadata)(nil),          // 4: osac.private.v1.Metadata
}
var file_osac_private_v1_role_binding_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.RoleBinding.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.RoleBinding.spec:type_name -> osac.private.v1.RoleBindingSpec
	3, // 2: osac.private.v1.RoleBinding.status:type_name -> osac.private.v1.RoleBindingStatus
	0, // 3: osac.private.v1.RoleBindingStatus.state:type_name -> osac.private.v1.RoleBindingState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_role_binding_type_proto_init() }
func file_osac_private_v1_role_binding_type_proto_init() {
	if File_osac_private_v1_role_binding_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_role_binding_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_role_binding_type_proto_rawDesc), len(file_osac_private_v1_role_binding_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_role_binding_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_role_binding_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_role_binding_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_role_binding_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_role_binding_type_proto = out.File
	file_osac_private_v1_role_binding_type_proto_goTypes = nil
	file_osac_private_v1_role_binding_type_proto_depIdxs = nil
}
