//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/role_bindings_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoleBindings_List_FullMethodName   = "/osac.private.v1.RoleBindings/List"
	RoleBindings_Get_FullMethodName    = "/osac.private.v1.RoleBindings/Get"
	RoleBindings_Create_FullMethodName = "/osac.private.v1.RoleBindings/Create"
	RoleBindings_Update_FullMethodName = "/osac.private.v1.RoleBindings/Update"
	RoleBindings_Delete_FullMethodName = "/osac.private.v1.RoleBindings/Delete"
	RoleBindings_Signal_FullMethodName = "/osac.private.v1.RoleBindings/Signal"
)

// RoleBindingsClient is the client API for RoleBindings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for managing role bindings.
//
// Role bindings grant the permissions defined by a role to a set of subjects (groups). The groups referenced in a
// role binding are identified by their identity provider (IDP) identifiers, as this service does not manage groups
// directly. Only administrators can create, update, or delete role bindings.
type RoleBindingsClient interface {
	// Retrieves the list of role bindings.
	List(ctx context.Context, in *RoleBindingsListRequest, opts ...grpc.CallOption) (*RoleBindingsListResponse, error)
	// Retrieves the details of one specific role binding.
	Get(ctx context.Context, in *RoleBindingsGetRequest, opts ...grpc.CallOption) (*RoleBindingsGetResponse, error)
	// Creates a new role binding.
	Create(ctx context.Context, in *RoleBindingsCreateRequest, opts ...grpc.CallOption) (*RoleBindingsCreateResponse, error)
	// Updates an existing role binding.
	Update(ctx context.Context, in *RoleBindingsUpdateRequest, opts ...grpc.CallOption) (*RoleBindingsUpdateResponse, error)
	// Deletes a role binding.
	Delete(ctx context.Context, in *RoleBindingsDeleteRequest, opts ...grpc.CallOption) (*RoleBindingsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *RoleBindingsSignalRequest, opts ...grpc.CallOption) (*RoleBindingsSignalResponse, error)
}

type roleBindingsClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleBindingsClient(cc grpc.ClientConnInterface) RoleBindingsClient {
	return &roleBindingsClient{cc}
}

func (c *roleBindingsClient) List(ctx context.Context, in *RoleBindingsListRequest, opts ...grpc.CallOption) (*RoleBindingsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleBindingsListResponse)
	err := c.cc.Invoke(ctx, RoleBindings_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBindingsClient) Get(ctx context.Context, in *RoleBindingsGetRequest, opts ...grpc.CallOption) (*RoleBindingsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleBindingsGetResponse)
	err := c.cc.Invoke(ctx, RoleBindings_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBindingsClient) Create(ctx context.Context, in *RoleBindingsCreateRequest, opts ...grpc.CallOption) (*RoleBindingsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleBindingsCreateResponse)
	err := c.cc.Invoke(ctx, RoleBindings_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBindingsClient) Update(ctx context.Context, in *RoleBindingsUpdateRequest, opts ...grpc.CallOption) (*RoleBindingsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleBindingsUpdateResponse)
	err := c.cc.Invoke(ctx, RoleBindings_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBindingsClient) Delete(ctx context.Context, in *RoleBindingsDeleteRequest, opts ...grpc.CallOption) (*RoleBindingsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleBindingsDeleteResponse)
	err := c.cc.Invoke(ctx, RoleBindings_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBindingsClient) Signal(ctx context.Context, in *RoleBindingsSignalRequest, opts ...grpc.CallOption) (*RoleBindingsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleBindingsSignalResponse)
	err := c.cc.Invoke(ctx, RoleBindings_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleBindingsServer is the server API for RoleBindings service.
// All implementations must embed UnimplementedRoleBindingsServer
// for forward compatibility.
//
// Service for managing role bindings.
//
// Role bindings grant the permissions defined by a role to a set of subjects (groups). The groups referenced in a
// role binding are identified by their identity provider (IDP) identifiers, as this service does not manage groups
// directly. Only administrators can create, update, or delete role bindings.
type RoleBindingsServer interface {
	// Retrieves the list of role bindings.
	List(context.Context, *RoleBindingsListRequest) (*RoleBindingsListResponse, error)
	// Retrieves the details of one specific role binding.
	Get(context.Context, *RoleBindingsGetRequest) (*RoleBindingsGetResponse, error)
	// Creates a new role binding.
	Create(context.Context, *RoleBindingsCreateRequest) (*RoleBindingsCreateResponse, error)
	// Updates an existing role binding.
	Update(context.Context, *RoleBindingsUpdateRequest) (*RoleBindingsUpdateResponse, error)
	// Deletes a role binding.
	Delete(context.Context, *RoleBindingsDeleteRequest) (*RoleBindingsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *RoleBindingsSignalRequest) (*RoleBindingsSignalResponse, error)
	mustEmbedUnimplementedRoleBindingsServer()
}

// UnimplementedRoleBindingsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleBindingsServer struct{}

func (UnimplementedRoleBindingsServer) List(context.Context, *RoleBindingsListRequest) (*RoleBindingsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRoleBindingsServer) Get(context.Context, *RoleBindingsGetRequest) (*RoleBindingsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRoleBindingsServer) Create(context.Context, *RoleBindingsCreateRequest) (*RoleBindingsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRoleBindingsServer) Update(context.Context, *RoleBindingsUpdateRequest) (*RoleBindingsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRoleBindingsServer) Delete(context.Context, *RoleBindingsDeleteRequest) (*RoleBindingsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRoleBindingsServer) Signal(context.Context, *RoleBindingsSignalRequest) (*RoleBindingsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedRoleBindingsServer) mustEmbedUnimplementedRoleBindingsServer() {}
func (UnimplementedRoleBindingsServer) testEmbeddedByValue()                      {}

// UnsafeRoleBindingsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleBindingsServer will
// result in compilation errors.
type UnsafeRoleBindingsServer interface {
	mustEmbedUnimplementedRoleBindingsServer()
}

func RegisterRoleBindingsServer(s grpc.ServiceRegistrar, srv RoleBindingsServer) {
	// If the following call pancis, it indicates UnimplementedRoleBindingsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleBindings_ServiceDesc, srv)
}

func _RoleBindings_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBindingsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleBindings_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBindingsServer).List(ctx, req.(*RoleBindingsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBindings_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBindingsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleBindings_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBindingsServer).Get(ctx, req.(*RoleBindingsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBindings_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBindingsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleBindings_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBindingsServer).Create(ctx, req.(*RoleBindingsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBindings_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBindingsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleBindings_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBindingsServer).Update(ctx, req.(*RoleBindingsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBindings_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBindingsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleBindings_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBindingsServer).Delete(ctx, req.(*RoleBindingsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBindings_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBindingsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleBindings_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBindingsServer).Signal(ctx, req.(*RoleBindingsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleBindings_ServiceDesc is the grpc.ServiceDesc for RoleBindings service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleBindings_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.RoleBindings",
	HandlerType: (*RoleBindingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RoleBindings_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RoleBindings_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RoleBindings_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RoleBindings_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RoleBindings_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _RoleBindings_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/role_bindings_service.proto",
}
