//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/role_bindings_service.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for listing role bindings.
type RoleBindingsListRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Index of the first result. If not specified the default value will be zero.
	Offset *int32 `protobuf:"varint,1,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all role bindings
	// for a specific role:
	//
	//	this.spec.role == "019dd9f6-36cb-7824-ac1c-6455d8a7a9b5"
	//
	// If this isn't provided, or if the value is empty, then all the role bindings that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the role binding instead of the names of the columns of a table. For example, in order
	// to sort the role bindings descending by name the value should be:
	//
	//	metadata.name desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order         *string `protobuf:"bytes,4,opt,name=order,proto3,oneof" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsListRequest) Reset() {
	*x = RoleBindingsListRequest{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsListRequest) ProtoMessage() {}

func (x *RoleBindingsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsListRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *RoleBindingsListRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *RoleBindingsListRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *RoleBindingsListRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *RoleBindingsListRequest) SetOffset(v int32) {
	x.Offset = &v
}

func (x *RoleBindingsListRequest) SetLimit(v int32) {
	x.Limit = &v
}

func (x *RoleBindingsListRequest) SetFilter(v string) {
	x.Filter = &v
}

func (x *RoleBindingsListRequest) SetOrder(v string) {
	x.Order = &v
}

func (x *RoleBindingsListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return x.Offset != nil
}

func (x *RoleBindingsListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.Limit != nil
}

func (x *RoleBindingsListRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.Filter != nil
}

func (x *RoleBindingsListRequest) HasOrder() bool {
	if x == nil {
		return false
	}
	return x.Order != nil
}

func (x *RoleBindingsListRequest) ClearOffset() {
	x.Offset = nil
}

func (x *RoleBindingsListRequest) ClearLimit() {
	x.Limit = nil
}

func (x *RoleBindingsListRequest) ClearFilter() {
	x.Filter = nil
}

func (x *RoleBindingsListRequest) ClearOrder() {
	x.Order = nil
}

type RoleBindingsListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Index of the first result. If not specified the default value will be zero.
	Offset *int32
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all role bindings
	// for a specific role:
	//
	//	this.spec.role == "019dd9f6-36cb-7824-ac1c-6455d8a7a9b5"
	//
	// If this isn't provided, or if the value is empty, then all the role bindings that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the role binding instead of the names of the columns of a table. For example, in order
	// to sort the role bindings descending by name the value should be:
	//
	//	metadata.name desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order *string
}

func (b0 RoleBindingsListRequest_builder) Build() *RoleBindingsListRequest {
	m0 := &RoleBindingsListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Offset = b.Offset
	x.Limit = b.Limit
	x.Filter = b.Filter
	x.Order = b.Order
	return m0
}

// Response message for listing role bindings.
type RoleBindingsListResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or if the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// List of results.
	Items         []*RoleBinding `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsListResponse) Reset() {
	*x = RoleBindingsListResponse{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsListResponse) ProtoMessage() {}

func (x *RoleBindingsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RoleBindingsListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RoleBindingsListResponse) GetItems() []*RoleBinding {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RoleBindingsListResponse) SetSize(v int32) {
	x.Size = v
}

func (x *RoleBindingsListResponse) SetTotal(v int32) {
	x.Total = v
}

func (x *RoleBindingsListResponse) SetItems(v []*RoleBinding) {
	x.Items = v
}

type RoleBindingsListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or if the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32
	// List of results.
	Items []*RoleBinding
}

func (b0 RoleBindingsListResponse_builder) Build() *RoleBindingsListResponse {
	m0 := &RoleBindingsListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Size = b.Size
	x.Total = b.Total
	x.Items = b.Items
	return m0
}

// Request message for getting a single role binding.
type RoleBindingsGetRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the role binding to retrieve.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsGetRequest) Reset() {
	*x = RoleBindingsGetRequest{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsGetRequest) ProtoMessage() {}

func (x *RoleBindingsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBindingsGetRequest) SetId(v string) {
	x.Id = v
}

type RoleBindingsGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the role binding to retrieve.
	Id string
}

func (b0 RoleBindingsGetRequest_builder) Build() *RoleBindingsGetRequest {
	m0 := &RoleBindingsGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

// Response message for getting a single role binding.
type RoleBindingsGetResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The requested role binding object.
	Object        *RoleBinding `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsGetResponse) Reset() {
	*x = RoleBindingsGetResponse{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsGetResponse) ProtoMessage() {}

func (x *RoleBindingsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsGetResponse) GetObject() *RoleBinding {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *RoleBindingsGetResponse) SetObject(v *RoleBinding) {
	x.Object = v
}

func (x *RoleBindingsGetResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *RoleBindingsGetResponse) ClearObject() {
	x.Object = nil
}

type RoleBindingsGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The requested role binding object.
	Object *RoleBinding
}

func (b0 RoleBindingsGetResponse_builder) Build() *RoleBindingsGetResponse {
	m0 := &RoleBindingsGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

// Request message for creating a new role binding.
type RoleBindingsCreateRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The role binding object to create.
	Object        *RoleBinding `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsCreateRequest) Reset() {
	*x = RoleBindingsCreateRequest{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsCreateRequest) ProtoMessage() {}

func (x *RoleBindingsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsCreateRequest) GetObject() *RoleBinding {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *RoleBindingsCreateRequest) SetObject(v *RoleBinding) {
	x.Object = v
}

func (x *RoleBindingsCreateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *RoleBindingsCreateRequest) ClearObject() {
	x.Object = nil
}

type RoleBindingsCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The role binding object to create.
	Object *RoleBinding
}

func (b0 RoleBindingsCreateRequest_builder) Build() *RoleBindingsCreateRequest {
	m0 := &RoleBindingsCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

// Response message for creating a new role binding.
type RoleBindingsCreateResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The created role binding object, including any server-generated fields.
	Object        *RoleBinding `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsCreateResponse) Reset() {
	*x = RoleBindingsCreateResponse{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsCreateResponse) ProtoMessage() {}

func (x *RoleBindingsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsCreateResponse) GetObject() *RoleBinding {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *RoleBindingsCreateResponse) SetObject(v *RoleBinding) {
	x.Object = v
}

func (x *RoleBindingsCreateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *RoleBindingsCreateResponse) ClearObject() {
	x.Object = nil
}

type RoleBindingsCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The created role binding object, including any server-generated fields.
	Object *RoleBinding
}

func (b0 RoleBindingsCreateResponse_builder) Build() *RoleBindingsCreateResponse {
	m0 := &RoleBindingsCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

// Request message for updating an existing role binding.
type RoleBindingsUpdateRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The role binding object with updated fields.
	Object *RoleBinding `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Field mask specifying which fields to update. If not provided, all fields will be updated.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock          bool `protobuf:"varint,3,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsUpdateRequest) Reset() {
	*x = RoleBindingsUpdateRequest{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsUpdateRequest) ProtoMessage() {}

func (x *RoleBindingsUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsUpdateRequest) GetObject() *RoleBinding {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *RoleBindingsUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *RoleBindingsUpdateRequest) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

func (x *RoleBindingsUpdateRequest) SetObject(v *RoleBinding) {
	x.Object = v
}

func (x *RoleBindingsUpdateRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.UpdateMask = v
}

func (x *RoleBindingsUpdateRequest) SetLock(v bool) {
	x.Lock = v
}

func (x *RoleBindingsUpdateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *RoleBindingsUpdateRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.UpdateMask != nil
}

func (x *RoleBindingsUpdateRequest) ClearObject() {
	x.Object = nil
}

func (x *RoleBindingsUpdateRequest) ClearUpdateMask() {
	x.UpdateMask = nil
}

type RoleBindingsUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The role binding object with updated fields.
	Object *RoleBinding
	// Field mask specifying which fields to update. If not provided, all fields will be updated.
	UpdateMask *fieldmaskpb.FieldMask
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock bool
}

func (b0 RoleBindingsUpdateRequest_builder) Build() *RoleBindingsUpdateRequest {
	m0 := &RoleBindingsUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	x.UpdateMask = b.UpdateMask
	x.Lock = b.Lock
	return m0
}

// Response message for updating an existing role binding.
type RoleBindingsUpdateResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The updated role binding object.
	Object        *RoleBinding `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsUpdateResponse) Reset() {
	*x = RoleBindingsUpdateResponse{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsUpdateResponse) ProtoMessage() {}

func (x *RoleBindingsUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsUpdateResponse) GetObject() *RoleBinding {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *RoleBindingsUpdateResponse) SetObject(v *RoleBinding) {
	x.Object = v
}

func (x *RoleBindingsUpdateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *RoleBindingsUpdateResponse) ClearObject() {
	x.Object = nil
}

type RoleBindingsUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The updated role binding object.
	Object *RoleBinding
}

func (b0 RoleBindingsUpdateResponse_builder) Build() *RoleBindingsUpdateResponse {
	m0 := &RoleBindingsUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

// Request message for deleting a role binding.
type RoleBindingsDeleteRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the role binding to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsDeleteRequest) Reset() {
	*x = RoleBindingsDeleteRequest{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsDeleteRequest) ProtoMessage() {}

func (x *RoleBindingsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBindingsDeleteRequest) SetId(v string) {
	x.Id = v
}

type RoleBindingsDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the role binding to delete.
	Id string
}

func (b0 RoleBindingsDeleteRequest_builder) Build() *RoleBindingsDeleteRequest {
	m0 := &RoleBindingsDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

// Response message for deleting a role binding.
type RoleBindingsDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsDeleteResponse) Reset() {
	*x = RoleBindingsDeleteResponse{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsDeleteResponse) ProtoMessage() {}

func (x *RoleBindingsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RoleBindingsDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RoleBindingsDeleteResponse_builder) Build() *RoleBindingsDeleteResponse {
	m0 := &RoleBindingsDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Request message for signaling a role binding.
type RoleBindingsSignalRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the role binding to signal.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsSignalRequest) Reset() {
	*x = RoleBindingsSignalRequest{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsSignalRequest) ProtoMessage() {}

func (x *RoleBindingsSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleBindingsSignalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBindingsSignalRequest) SetId(v string) {
	x.Id = v
}

type RoleBindingsSignalRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the role binding to signal.
	Id string
}

func (b0 RoleBindingsSignalRequest_builder) Build() *RoleBindingsSignalRequest {
	m0 := &RoleBindingsSignalRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

// Response message for signaling a role binding.
type RoleBindingsSignalResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingsSignalResponse) Reset() {
	*x = RoleBindingsSignalResponse{}
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingsSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingsSignalResponse) ProtoMessage() {}

func (x *RoleBindingsSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_role_bindings_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RoleBindingsSignalResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RoleBindingsSignalResponse_builder) Build() *RoleBindingsSignalResponse {
	m0 := &RoleBindingsSignalResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_role_bindings_service_proto protoreflect.FileDescriptor

var file_osac_private_v1_role_bindings_service_proto_rawDesc = string([]byte{
	0x0a, 0x2b, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x65,
	0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x78, 0x0a,
	0x18, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x52, 0x6f, 0x6c, 0x65, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x4f, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x22, 0x51, 0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x34, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x52, 0x0a, 0x1a, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x19, 0x52, 0x6f,
	0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x52,
	0x0a, 0x1a, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1c, 0x0a, 0x1a, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a,
	0x19, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x52, 0x6f,
	0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd9, 0x06, 0x0a, 0x0c, 0x52, 0x6f, 0x6c,
	0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x82, 0x01, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12,
	0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x8c,
	0x01, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x2c, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x22, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x98, 0x01,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x35, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2f, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0xa4, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x41, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x3b, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x32, 0x29, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x2f, 0x7b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x69, 0x64, 0x7d, 0x12,
	0x8d, 0x01, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x2a, 0x22, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12,
	0x63, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x2a, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0xdd, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x18, 0x52, 0x6f,
	0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f,
	0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_role_bindings_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_osac_private_v1_role_bindings_service_proto_goTypes = []any{
	(*RoleBindingsListRequest)(nil),    // 0: osac.private.v1.RoleBindingsListRequest
	(*RoleBindingsListResponse)(nil),   // 1: osac.private.v1.RoleBindingsListResponse
	(*RoleBindingsGetRequest)(nil),     // 2: osac.private.v1.RoleBindingsGetRequest
	(*RoleBindingsGetResponse)(nil),    // 3: osac.private.v1.RoleBindingsGetResponse
	(*RoleBindingsCreateRequest)(nil),  // 4: osac.private.v1.RoleBindingsCreateRequest
	(*RoleBindingsCreateResponse)(nil), // 5: osac.private.v1.RoleBindingsCreateResponse
	(*RoleBindingsUpdateRequest)(nil),  // 6: osac.private.v1.RoleBindingsUpdateRequest
	(*RoleBindingsUpdateResponse)(nil), // 7: osac.private.v1.RoleBindingsUpdateResponse
	(*RoleBindingsDeleteRequest)(nil),  // 8: osac.private.v1.RoleBindingsDeleteRequest
	(*RoleBindingsDeleteResponse)(nil), // 9: osac.private.v1.RoleBindingsDeleteResponse
	(*RoleBindingsSignalRequest)(nil),  // 10: osac.private.v1.RoleBindingsSignalRequest
	(*RoleBindingsSignalResponse)(nil), // 11: osac.private.v1.RoleBindingsSignalResponse
	(*RoleBinding)(nil),                // 12: osac.private.v1.RoleBinding
	(*fieldmaskpb.FieldMask)(nil),      // 13: google.protobuf.FieldMask
}
var file_osac_private_v1_role_bindings_service_proto_depIdxs = []int32{
	12, // 0: osac.private.v1.RoleBindingsListResponse.items:type_name -> osac.private.v1.RoleBinding
	12, // 1: osac.private.v1.RoleBindingsGetResponse.object:type_name -> osac.private.v1.RoleBinding
	12, // 2: osac.private.v1.RoleBindingsCreateRequest.object:type_name -> osac.private.v1.RoleBinding
	12, // 3: osac.private.v1.RoleBindingsCreateResponse.object:type_name -> osac.private.v1.RoleBinding
	12, // 4: osac.private.v1.RoleBindingsUpdateRequest.object:type_name -> osac.private.v1.RoleBinding
	13, // 5: osac.private.v1.RoleBindingsUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 6: osac.private.v1.RoleBindingsUpdateResponse.object:type_name -> osac.private.v1.RoleBinding
	0,  // 7: osac.private.v1.RoleBindings.List:input_type -> osac.private.v1.RoleBindingsListRequest
	2,  // 8: osac.private.v1.RoleBindings.Get:input_type -> osac.private.v1.RoleBindingsGetRequest
	4,  // 9: osac.private.v1.RoleBindings.Create:input_type -> osac.private.v1.RoleBindingsCreateRequest
	6,  // 10: osac.private.v1.RoleBindings.Update:input_type -> osac.private.v1.RoleBindingsUpdateRequest
	8,  // 11: osac.private.v1.RoleBindings.Delete:input_type -> osac.private.v1.RoleBindingsDeleteRequest
	10, // 12: osac.private.v1.RoleBindings.Signal:input_type -> osac.private.v1.RoleBindingsSignalRequest
	1,  // 13: osac.private.v1.RoleBindings.List:output_type -> osac.private.v1.RoleBindingsListResponse
	3,  // 14: osac.private.v1.RoleBindings.Get:output_type -> osac.private.v1.RoleBindingsGetResponse
	5,  // 15: osac.private.v1.RoleBindings.Create:output_type -> osac.private.v1.RoleBindingsCreateResponse
	7,  // 16: osac.private.v1.RoleBindings.Update:output_type -> osac.private.v1.RoleBindingsUpdateResponse
	9,  // 17: osac.private.v1.RoleBindings.Delete:output_type -> osac.private.v1.RoleBindingsDeleteResponse
	11, // 18: osac.private.v1.RoleBindings.Signal:output_type -> osac.private.v1.RoleBindingsSignalResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_osac_private_v1_role_bindings_service_proto_init() }
func file_osac_private_v1_role_bindings_service_proto_init() {
	if File_osac_private_v1_role_bindings_service_proto != nil {
		return
	}
	file_osac_private_v1_role_binding_type_proto_init()
	file_osac_private_v1_role_bindings_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_role_bindings_service_proto_rawDesc), len(file_osac_private_v1_role_bindings_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osac_private_v1_role_bindings_service_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_role_bindings_service_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_role_bindings_service_proto_msgTypes,
	}.Build()
	File_osac_private_v1_role_bindings_service_proto = out.File
	file_osac_private_v1_role_bindings_service_proto_goTypes = nil
	file_osac_private_v1_role_bindings_service_proto_depIdxs = nil
}
