apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osac-console-proxy-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osac-console-proxy-secret-reader
subjects:
- kind: ServiceAccount
  name: osac-console-proxy
